# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: angularjs-on-rails 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "angularjs-on-rails"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Rajendran S"]
  s.date = "2014-06-23"
  s.description = "AngularJS on Rails wraps the AngularJS 1.2.18 library for use in Rails 3.1 and above. This project is an application skeleton for a typical AngularJS web app. You can use it to quickly bootstrap your angular webapp projects"
  s.email = "rajendran.s@optisolbusiness.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "app/assets/javascripts/angular-animate.js",
    "app/assets/javascripts/angular-cookies.js",
    "app/assets/javascripts/angular-loader.js",
    "app/assets/javascripts/angular-mocks.js",
    "app/assets/javascripts/angular-resource.js",
    "app/assets/javascripts/angular-route.js",
    "app/assets/javascripts/angular-sanitize.js",
    "app/assets/javascripts/angular-scenario.js",
    "app/assets/javascripts/angular-touch.js",
    "app/assets/javascripts/angular.js",
    "lib/angularjs-on-rails.rb",
    "lib/angularjs-on-rails/version.rb",
    "lib/generators/angular/install/install_generator.rb",
    "lib/generators/angular/install/templates/app.coffee",
    "lib/generators/angular/install/templates/index.html",
    "lib/generators/angular/resource_helpers.rb"
  ]
  s.homepage = "http://github.com/raj-optisol/angularjs-on-rails"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Easily setup and use AngularJS with Rails 3.1 and greater"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

